# Generated by Django 5.0.1 on 2024-01-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_data',
            new_name='due_date',
        ),
    ]
